Add more tile intrinsic functions
s22s/rasterframes pull request #9
Opened 2019-03-13 20:08 UTC by vpipkt

* round
* log including base 10, base 2, and minus 1
* exp including base 10, base 2, and plus 1

2019-03-13 20:10 UTC, vpipkt commented on core/src/main/scala/astraea/spark/rasterframes/expressions/localops/Round.scala
> +//  import astraea.spark.rasterframes.encoders.StandardEncoders.PrimitiveEncoders.doubleEnc
remove

2019-03-13 20:31 UTC, vpipkt commented
Should I have added tests to `PyRasterFramesTests.py`?

2019-03-15 13:44 UTC, metasim requested changes
Can you add update the reference section of the manual you wrote with your additions. We need to start keeping all those bits in sync. Of course I'm tempted to have that page automatically generated in code, but I know that's not what I need to be working on now.... ;-)

2019-03-18 17:08 UTC, metasim commented
@vpipkt The Python tests are really weak right now... I'd like to get them to the place where each function is at least called from Python, as it will scare up most problems. Not putting that all on you, but small steps are big steps.

2019-03-19 13:10 UTC, vpipkt commented
@metasim I'll put up a PR for the docs changes and you can merge at the same time. I'll probably put up a little work on the python tests as it will help me with both efforts.

2019-03-19 15:19 UTC, vpipkt commented
See doc update here https://github.com/s22s/earthai-documentation/pull/23

2019-03-20 23:23 UTC, metasim approved these changes

2019-03-20 23:33 UTC, merged